"""add_user_id_to_blacklisted_tokens

Revision ID: 9e1f2b4e1bc8
Revises: d211b59584bd
Create Date: 2026-05-19 16:07:44.100932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1f2b4e1bc8'
down_revision: Union[str, None] = 'd211b59584bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blacklisted_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_Blacklisted_tokens_id'), table_name='Blacklisted_tokens')
    op.create_index(op.f('ix_Blacklisted_tokens_user_id'), 'Blacklisted_tokens', ['user_id'], unique=False)
    op.drop_column('Blacklisted_tokens', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Blacklisted_tokens', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_Blacklisted_tokens_user_id'), table_name='Blacklisted_tokens')
    op.create_index(op.f('ix_Blacklisted_tokens_id'), 'Blacklisted_tokens', ['id'], unique=False)
    op.drop_column('Blacklisted_tokens', 'user_id')
    # ### end Alembic commands ###
