"""Add blacklisted token

Revision ID: d211b59584bd
Revises: 6a191353801b
Create Date: 2026-05-19 13:38:58.367176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd211b59584bd'
down_revision: Union[str, None] = '6a191353801b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Blacklisted_tokens_id'), 'Blacklisted_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_Blacklisted_tokens_token'), 'Blacklisted_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Blacklisted_tokens_token'), table_name='Blacklisted_tokens')
    op.drop_index(op.f('ix_Blacklisted_tokens_id'), table_name='Blacklisted_tokens')
    op.drop_table('Blacklisted_tokens')
    # ### end Alembic commands ###
